# Basic settings
title: C100
tagline: a kitchen tools journal
description: A monthly, online journal on food and the tools we use to make it
analytics_id: UA-25940549-15

# Network settings
baseurl: ""
url: https://c100.co/
host: 0.0.0.0

# Build settings
permalink: /:categories/:title/
sass:
  sass_dir: _sass
  style: :compressed

# Social settings
email: editor@c100.co
twitter: c100journal
instagram: c100journal
facebook: c100journal
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      thumbnail: default.png
      illo: default.png
      is_post: true
  - scope:
      path: ""
      type: "issues"
    values:
      layout: issue
      volume: 0
      color: ffffff
      cover: default.png
      is_issue: true
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: recipe
      tags: recipes
      volume: 0
      thumbnail: default.png
      illo: default.png
      is_post: true

# Collection settings
collections:
  issues:
    output: true
    permalink: /:title/
    sort_by: volume
  recipes:
    output: true
    permalink: /recipes/:title/
    sort_by: volume

# Pagination settings
pagination:
  enabled: true
  title: ':title &middot; :num'
  per_page: 10
  permalink: '/:num/'
  sort_reverse: true

# Markdown settings
kramdown:
  footnote_backlink: '&#x21a9;&#xFE0E;'

# Gem settings
plugins:
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-extlinks

extlinks:
  attributes: {target: _blank}

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - "*.code-workspace"
