# Basic settings
title: C100
tagline: "a kitchen tools journal"
description: "A monthly, online journal on food and the tools we use to make it."
email: editor@c100.co
analytics_id: UA-25940549-15

# Social settings
twitter: c100journal
instagram: c100journal
facebook: c100journal

# Network settings
baseurl: ""
url: "http://c100.co"
port: 8888

# Build settings
paginate: 1
permalink: /:categories/:title/
sass:
  sass_dir: _sass
  style: :compressed

# Gem settings
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

extlinks:
  attributes: {target: _blank}