# Basic settings
title: C100
tagline: a kitchen tools journal
description: A monthly, online journal on food and the tools we use to make it
analytics_id: UA-25940549-15

# Network settings
baseurl: ""
url: http://c100.co

# Build settings
paginate: 1
permalink: /:categories/:title/
sass:
  sass_dir: _sass
  style: :compressed

# Social settings
twitter: c100journal
instagram: c100journal
facebook: c100journal

# Gem settings
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-extlinks

extlinks:
  attributes: {target: _blank}

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
