languageCode = "en-us"
baseurl = "http://c100.co/"
title = "C100"
googleAnalytics = ""
disqusShortname = "c100"
paginate = 10
paginatePath = "page"
footnotereturnlinkcontents = "↩"
[permalinks]
	post = "/:year/:month/:title/"
pygmentsStyle = "monokai"
[blackfriday]
	hrefTargetBlank = true
[params]
	name = "C100"
	description = "Work in progress"
	author = "Basheer Tome"
	bio = "Work in progress"
